Hbonds
chemfiles/cfiles pull request #18
Opened 2017-04-07 12:34 UTC by lscalfi

2017-04-07 13:24 UTC, Luthaf commented
Great to see this! Thanks for submitting the PR. 

I know we talked about this in person, but could you add a small description in the initial PR comment next time? This allow external readers to see what is going on.

2017-04-07 13:46 UTC, Luthaf requested changes
Great work for a first time with C++! Here are a lot of comments, but don't be afraid, all of them are easy to change.

We also need to think a bit more about the output format. Currently it is not self describing (we need a comment telling what is in each column of the output); and multiple timesteps are not separated.

2017-04-07 13:46 UTC, Luthaf commented on src/commands/HBonds.cpp
> +R"(Compute list of hydrogen bonds along a trajectory. A selection can be specified using the
"A selection can be specified .." => "Selections for the acceptor and donor atoms can be specified ..."

2017-04-07 13:46 UTC, Luthaf commented on src/commands/HBonds.cpp
> +can be specified (donor-acceptor distance and donor-acceptor-H angle)
Maybe add an explanation/comment about how the hydrogen bonds are detected? (using geometrical criteria)

2017-04-07 13:46 UTC, Luthaf commented on src/commands/HBonds.cpp
> +http://chemfiles.github.io/chemfiles/latest/selections.html
can you change the URL to `http://chemfiles.org/chemfiles/...`?

2017-04-07 13:46 UTC, Luthaf commented on src/commands/HBonds.cpp
> +  cfiles hbonds in.zeo out.mol --input-format=XYZ --output-format=PDB
These examples make no sense. copy/paste error ?

2017-04-07 13:46 UTC, Luthaf commented on src/commands/HBonds.cpp
> +  --selection_acceptor=<sel>    selection to use for the acceptors. This must be a
How about `--acceptors` for the argument name?

2017-04-07 13:46 UTC, Luthaf commented on src/commands/HBonds.cpp
> +  --selection_donor=<sel>       selection to use for the donors. This must be a
Same here, how about `--donnors`

2017-04-07 13:46 UTC, Luthaf commented on src/commands/HBonds.cpp
> +                                [default: atoms: not type H]
Shouldn't the default be `type O or type N or type F `?

2017-04-07 13:46 UTC, Luthaf commented on src/commands/HBonds.cpp
> +  -p <par>, --parameters=<par>  parameters to use for the hydrogen bond. <par>
I would use two separated parameters here: `--distance` and `--angle`

2017-04-07 13:46 UTC, Luthaf commented on src/commands/HBonds.cpp
> +    options_str += OPTIONS;
Can you add your author informations here? 

```cpp
auto options_str = command_header("hbonds", HBonds().description());
options_str += "Laura Scalfi <email>\n";
options_str += OPTIONS;
```

2017-04-07 13:46 UTC, Luthaf commented on src/commands/HBonds.hpp
> +	std::string selectionAcceptor;
Can you use `snake_case` here?

2017-04-07 13:46 UTC, Luthaf commented on src/commands/HBonds.hpp
> +    chemfiles::Selection selectionAcceptor_;
Can you use `snake_case` here too?

2017-04-07 13:46 UTC, Luthaf commented on src/commands/HBonds.hpp
> +    HBonds(): selectionAcceptor_("bonds: type(#2) == H"), selectionDonor_("not type H") {}
Please do not provide defaults both here and in the doctopt `OPTIONS` string. There should be only one source of information to keep it [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself).

2017-04-07 13:46 UTC, Luthaf commented on src/commands/HBonds.cpp
> +        options.outfile = options.trajectory + "_hb.dat";
This does not match the documentation.

2017-04-07 13:46 UTC, Luthaf commented on src/commands/HBonds.cpp
> +	}
Please use 4-spaces for indent (here and two lines below)

2017-04-07 13:46 UTC, Luthaf commented on src/commands/HBonds.cpp
> +	    options.angle_parameter = stod(splitted[1])*pi/180;
What happens if `splitted[0] == "hviousbo"` ? (look for `std::invalid_argument` [here](http://en.cppreference.com/w/cpp/string/basic_string/stof))

2017-04-07 13:46 UTC, Luthaf commented on src/commands/HBonds.cpp
> +        throw CFilesError("Can not use a selection for acceptors with size different than 2.");
You require `bonds:` selection in the documentation, but the selection could be of kind `pairs:` too here.

2017-04-07 13:46 UTC, Luthaf commented on src/commands/HBonds.cpp
> +            auto hydrogen = match[1];
What happens if the user provides acceptor selection like this: `bonds: name(#1) H and name(#2) O`?

2017-04-07 13:46 UTC, Luthaf commented on src/commands/HBonds.cpp
> +                        outfile << frame.topology()[donor].type() << donor << "   " << frame.topology()[acceptor].type() << acceptor << "   " << frame.topology()[hydrogen].type() << hydrogen << "  :
could you split this on multiple lines? It is really hard to read.

2017-04-07 14:49 UTC, lscalfi commented on src/commands/HBonds.cpp
> +  cfiles hbonds in.zeo out.mol --input-format=XYZ --output-format=PDB
oups!

2017-04-10 15:59 UTC, Luthaf commented on src/commands/HBonds.cpp
> +  cfiles hbonds protein.pdb --donors=="atoms: type N" -p 2.5:20.0
The syntax for parameters changed =)

2017-04-10 15:59 UTC, Luthaf commented on src/commands/HBonds.cpp
> +            else
Could you write this `} else {` in a single line to follow the rest of the code ?

2017-04-10 15:59 UTC, Luthaf commented on src/commands/HBonds.cpp
> +        outfile << "# donor-acceptor-H angle < " << options.angle*180/pi << " degrees" << std::endl;
This still misses a comment line describing the content of the file.

2017-04-10 15:59 UTC, Luthaf commented on src/commands/HBonds.cpp
> +                        outfile << frame.topology()[donor].type() << donor << "   ";
Why use `type` instead of `name` here?

2017-04-10 16:00 UTC, Luthaf commented
Can you add a test to ensure the coverage stays at least at the same level? 

This should be the last thing to do 😃 !

2017-04-11 10:04 UTC, Luthaf commented on src/commands/HBonds.cpp
> +        outfile << "# Donor (name index)   Acceptor (name index)   Hydrogen (name index)  : Distance D-A    Angle D-A-H" << std::endl;
Shouldn't this angle be D-H-A ?

2017-04-11 11:57 UTC, lscalfi commented on src/commands/HBonds.cpp
> +        outfile << "# Donor (name index)   Acceptor (name index)   Hydrogen (name index)  : Distance D-A    Angle D-A-H" << std::endl;
no, imagine this configuration:
                    D
   A-----H  
We want A, H and D to be the "most co-linear" possible. If the angle D-A-H is zero, then they are aligned, if not <e want the angle to be less than 30°.
By taking D-H-A, we would want it to be equal to 180° +/- 30°.

2017-04-11 13:19 UTC, Luthaf approved these changes

2017-04-11 13:20 UTC, merged

2017-04-11 13:20 UTC, Luthaf commented
Thank you again for this!